name: WebAssembly Node Package

on:
  release:
    types: [ created ]

permissions:
  id-token: write  # Required for OIDC
  contents: read

env:
  NODE_VERSION: 24
  EMSDK_VERSION: 3.1.26

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{ env.EMSDK_VERSION }}
        no-cache: true # https://github.com/mymindstorm/setup-emsdk/issues/20

    - run: make wasmopt

    - run: npm ci
      working-directory: webassembly
    - run: npm test
      working-directory: webassembly
    - run: npm ci --production
      working-directory: webassembly
    - run: npm publish
      working-directory: webassembly
